name: Migrate Repository-Level Secret Scanning Results Remediation State

on:
  issues:
    types: [opened, edited]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Validate PAT tokens
      run: |
        if [[ -z "${{ secrets.SOURCE_TOKEN }}" ]]; then
          echo "Source Token is missing!"
          exit 1
        fi
        if [[ -z "${{ secrets.TARGET_TOKEN }}" ]]; then
          echo "Target Token is missing!"
          exit 1
        fi
      shell: bash

    - name: Set up environment for GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run the PowerShell migration script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pwsh -File ./script/final.ps1 `
          -sourceOrg "${{ steps.issue_body.outputs.source_org }}" `
          -sourceRepo "${{ steps.issue_body.outputs.source_repo }}" `
          -targetOrg "${{ steps.issue_body.outputs.target_org }}" `
          -targetRepo "${{ steps.issue_body.outputs.target_repo }}" `
          -sourceToken "${{ secrets.SOURCE_TOKEN }}" `
          -targetToken "${{ secrets.TARGET_TOKEN }}"
      shell: pwsh
